### ISSUE TITLE
aplha set to 1 when using lighten, darken and other methods

### ISSUE THREAD

**Issue by MARTIMM** [zoffixznet/perl6-Color#10]
All changes on a color using these methods are setting the alpha back to one.
```
my Color $c .= new( :rgbad([1.0, 0.2, 0.4, 0.5]))     # set to #FF3366
say $c.rgbad                                          # OUTPUT (1 0.2 0.4 0.5)
say $c.lighten(10).rgbad                              # OUTPUT (1 0.4 0.55 1)
```
explicitly setting alpha-math doesn't help.

I think, but am not sure if alpha is involved in these calculations, that alpha must keep the same value.

Regards,
Marcel

**Comment by MARTIMM** [comment]
In Color::Conversion perhaps a method such as lighten could be rewritten like so
```
    method lighten ( Real $Δ ) {
        # save alpha
        my $alpha = self.rgbad[3]; 
        my $clr = Color.new( hsl => [ lighten( |self.hsl, $Δ ) ] );
        # restore alpha
        return Color.new( rgbad => ( | $clr.rgbd, $alpha) );
    }
```

**Comment by zoffixznet** [comment]
FWIW, don't think I'll have much time to hack on this module. And @holli-holzer did Color::Conversion modules.

I can give out commit bits if anyone wants to maintain this module and advance it to their liking.

**Comment by MARTIMM** [comment]
Well, I could change a bit here and there if you find the above suggestions good enough. If you give the commit bits, is it then enough to fork the project and commit changes from my computer instead of using the github interface? That's something I didn't do before. 

Btw, I really liked the advent blogs of yours. Gave me more understanding of quite a few perl6 things.

**Comment by zoffixznet** [comment]
Sent you an invite.

> is it then enough to fork the project and commit changes from my computer instead of using the github interface?

You can do that with any project, even without any commit bits. With the commit bit you simply **don't need to fork** and can commit directly.

**Comment by MARTIMM** [comment]
I've changed it by introducing the method alpha first, which get/set the alpha channel and alpha-math. With this, the methods were easier to change. e.g.
```
    method lighten ( Real $Δ ) {
        my Color $c .= new( hsl => [lighten( |self.hsl,  $Δ)]);
        $c.alpha($!a) unless $!a == 255;
        $c.alpha-math = $!alpha-math;
        $c
    }
```
as you can see alpha-math is also copied.
Version is now 1.002005
