### ISSUE TITLE
expose / export the color space conversion routines?

### ISSUE THREAD

**Issue by thundergnat** [zoffixznet/perl6-Color#4]
Any chance you could make the the rest of the color space conversion routines exported? I really wanted to use the hsv2rgb routine on http://rosettacode.org/wiki/Julia_set#Perl_6 but had to settle for pulling out a chopped down version of the routine. Thanks.

**Comment by zoffixznet** [comment]
I wouldn't mind if someone submited a PR with those conversion routines moved into Color::Functions (Color::Convert?) module. It would be imported by Color internally. And if a user wants to use those directly, they can `use` Color::Functions directly.

**Comment by zoffixznet** [comment]
Fixed in https://github.com/zoffixznet/perl6-Color/commit/ed4bebdc455b22a3e79d8d48a70c936467e1cf31
